export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'

export const GET_PROJECT = 'GET_PROJECT'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'

export const ADD_PROJECT = 'ADD_PROJECT'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'

export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'

export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'

export const GET_PROJECT_PAYMENTS = 'GET_PROJECT_PAYMENTS'
export const GET_PROJECT_PAYMENTS_SUCCESS = 'GET_PROJECT_PAYMENTS_SUCCESS'

export const ADD_PAYMENT = 'ADD_PAYMENT'
export const ADD_PAYMENT_SUCCESS = 'ADD_PAYMENT_SUCCESS'

export const UPDATE_PAYMENT = 'UPDATE_PAYMENT'
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS'

export const DELETE_PAYMENT = 'DELETE_PAYMENT'
export const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS'

export const GET_PROJECT_CREDENTIALS = 'GET_PROJECT_CREDENTIALS'
export const GET_PROJECT_CREDENTIALS_SUCCESS = 'GET_PROJECT_CREDENTIALS_SUCCESS'

export const ADD_CREDENTIAL = 'ADD_CREDENTIAL'
export const ADD_CREDENTIAL_SUCCESS = 'ADD_CREDENTIAL_SUCCESS'

export const UPDATE_CREDENTIAL = 'UPDATE_CREDENTIAL'
export const UPDATE_CREDENTIAL_SUCCESS = 'UPDATE_CREDENTIAL_SUCCESS'

export const DELETE_CREDENTIAL = 'DELETE_CREDENTIAL'
export const DELETE_CREDENTIAL_SUCCESS = 'DELETE_CREDENTIAL_SUCCESS'

export const GET_NOTES = 'GET_NOTES'
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'

export const EDIT_NOTE = 'EDIT_NOTE'
export const CLOSE_NOTE = 'CLOSE_NOTE'

export const UPDATE_NOTE = 'UPDATE_NOTE'
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS'

export const GET_CONTACTS = 'GET_CONTACTS'
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS'

export const GET_CONTACT = 'GET_CONTACT'
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS'

export const ADD_CONTACT = 'ADD_CONTACT'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'

export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'

export const DELETE_CONTACT = 'DELETE_CONTACT'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
